### ISSUE TITLE
Content-Type in HTTP Traffic marked as Email

### ISSUE THREAD

**Issue by malvidin** [CybercentreCanada/assemblyline-base#325]
https://github.com/CybercentreCanada/assemblyline-base/blob/a55d3273d800b2659acf094c73d656ddfce34d94/assemblyline/common/identify.py#L97

With this sample, it marks it as type "document/email", the EmlParser fails, and Suricata does not process the PCAP.
https://www.malware-traffic-analysis.net/2019/09/04/index.html

**Comment by cccs-kevin** [comment]
Hi @malvidin, thanks for creating this issue! 
I'm assuming you're talking about the sample found [here ](https://www.malware-traffic-analysis.net/2019/09/04/2019-09-04-Ursnif-infection-with-Trickbot.pcap.zip).
I was unable to reproduce the incorrect identification of the file, with the most up-to-date code from this repository that file was identified as `network/tcpdump`. If you do have the most up-to-date code and the issue is still persisting, let me know!

**Comment by malvidin** [comment]
Yes, that is the file. I am using Image Id `a3d8e2483fed` for the core (alerter, dispatcher, ingester, etc.)
```
MD5:  fad01871bb1bba5fd617818f630bcb1a
SHA1:  2c037b8dc499aa18991765ace400d610fbfc7a53
SHA256:  afe45037529455e1f52f7eebcb9f80cb688a8f92cab705a936ff9c18b05cf022
SSDEEP:  393216:85dK09Af39F933tzjQjzxY50Tr5gTOk9IFxGLIDS1Uj:85A0+3T9WHxD5gTODxG2GUj
Size: 18691200 (18 MB)
Type:  document/email
Mimetype:  application/vnd.tcpdump.pcap
Magic:  pcap capture file, microsecond ts (little-endian) - version 2.4 (Ethernet, capture length 65535) (Lepton 3.x), scale 0-0, spot sensor temperature 0.000000, color scheme 15, calibration: offset -0.000000, slope 0.000000
Entropy:  7.892249519737473
```

**Comment by cccs-kevin** [comment]
Okay okay, do you have the tags for those core images?

**Comment by malvidin** [comment]
RepoTags `cccs/assemblyline-core:4.0.stable`, the version in the Cmd is `4.0.0.82`
[docker_inspect_4.0.0.82.json.txt](https://github.com/CybercentreCanada/assemblyline-base/files/6983034/docker_inspect_4.0.0.82.json.txt)

**Comment by cccs-kevin** [comment]
Thanks for getting me that tag.
Just released new builds for the following repos:
[`cccs/assemblyline-core:4.0.0.stable84`](https://hub.docker.com/layers/cccs/assemblyline-core/4.0.0.stable84/images/sha256-02d6ff640205c5fa839c3d4e77c1a00e7cc527b0689ca0f618d2a9a14f1c9b51?context=explore)
[`cccs/assemblyline-ui:4.0.0.stable77`](https://hub.docker.com/layers/cccs/assemblyline-ui/4.0.0.stable77/images/sha256-ca0bcdc4b6450a133a2d4442581e8eb08aa39a530230fa4bb14014f990960782?context=explore)
[`cccs/assembyline-v4-service:4.0.0.stable8`](https://hub.docker.com/layers/cccs/assemblyline-v4-service-base/4.0.0.stable8/images/sha256-aa500b51d94cb62dc6873a7cddee06cc7bf6fb503522c9ddbdce8a5b9fa1916b?context=explore)
[`cccs/assemblyline-service-server:4.0.0.stable54`](https://hub.docker.com/layers/cccs/assemblyline-service-server/4.0.0.stable54/images/sha256-7fa74c0126963cfaa0c9130f13fec8234291fa0bf072d81eff6598d0f280ca1f?context=explore)

They should have the most up-to-date `identify.py` code. Let me know if that works!

**Comment by malvidin** [comment]
I pulled Image Id `a6545e1f7ded`. It has RepoTags `cccs/assemblyline-core:4.0.stable` and Cmd includes `version=4.0.0.84`.
Below is the hash of `identify.py` in the ingester container, which is based off of the core image, and the output from the PCAP. 
```
assemblyline@52b3ab744993:~$ sha1sum /var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline/common/identify.py
ae907be6fff6bb16bde4985d7edb1cf6aab39428  /var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline/common/identify.py

assemblyline@52b3ab744993:~$ python /var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline/common/identify.py test_input
{'ascii': '..........................o]&...V...V.............G...E..H......',
 'entropy': 7.892249519737473,
 'hex': 'd4c3b2a1020004000000000000000000ffff0000010000008bff6f5d26db0d005601000056010000ffffffffffff0008021c47ae080045000148001b00008011',
 'magic': 'pcap capture file, microsecond ts (little-endian) - version 2.4 '
          '(Ethernet, capture length 65535) (Lepton 3.x), scale 0-0, spot '
          'sensor temperature 0.000000, color scheme 15, calibration: offset '
          '-0.000000, slope 0.000000',
 'md5': 'fad01871bb1bba5fd617818f630bcb1a',
 'mime': 'application/vnd.tcpdump.pcap',
 'sha1': '2c037b8dc499aa18991765ace400d610fbfc7a53',
 'sha256': 'afe45037529455e1f52f7eebcb9f80cb688a8f92cab705a936ff9c18b05cf022',
 'size': 18691200,
 'ssdeep': '393216:85dK09Af39F933tzjQjzxY50Tr5gTOk9IFxGLIDS1Uj:85A0+3T9WHxD5gTODxG2GUj',
 'type': 'document/email'}
```

If the `Content-Type` expression is removed, the type returned is `code/ps1`.

```
assemblyline@4499352b3ab7:~$ python /var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline/common/identify.py test_input
{'ascii': '..........................o]&...V...V.............G...E..H......',
 'entropy': 7.892249519737473,
 'hex': 'd4c3b2a1020004000000000000000000ffff0000010000008bff6f5d26db0d005601000056010000ffffffffffff0008021c47ae080045000148001b00008011',
 'magic': 'pcap capture file, microsecond ts (little-endian) - version 2.4 '
          '(Ethernet, capture length 65535) (Lepton 3.x), scale 0-0, spot '
          'sensor temperature 0.000000, color scheme 15, calibration: offset '
          '-0.000000, slope 0.000000',
 'md5': 'fad01871bb1bba5fd617818f630bcb1a',
 'mime': 'application/vnd.tcpdump.pcap',
 'sha1': '2c037b8dc499aa18991765ace400d610fbfc7a53',
 'sha256': 'afe45037529455e1f52f7eebcb9f80cb688a8f92cab705a936ff9c18b05cf022',
 'size': 18691200,
 'ssdeep': '393216:85dK09Af39F933tzjQjzxY50Tr5gTOk9IFxGLIDS1Uj:85A0+3T9WHxD5gTODxG2GUj',
 'type': 'code/ps1'}
```

**Comment by cccs-kevin** [comment]
Thanks for sharing all of that information, I think we're getting closer to finding the culprit.

```
assemblyline@dev-box:~$ sha1sum ~/identify.py
ae907be6fff6bb16bde4985d7edb1cf6aab39428  ~/identify.py

assemblyline@dev-box:~$ python ~/identify.py afe45037529455e1f52f7eebcb9f80cb688a8f92cab705a936ff9c18b05cf022
{'ascii': '..........................o]&...V...V.............G...E..H......',
 'entropy': 7.892249519737473,
 'hex': 'd4c3b2a1020004000000000000000000ffff0000010000008bff6f5d26db0d005601000056010000ffffffffffff0008021c47ae080045000148001b00008011',
 'magic': 'tcpdump capture file (little-endian) - version 2.4 (Ethernet, '
          'capture length 65535)',
 'md5': 'fad01871bb1bba5fd617818f630bcb1a',
 'mime': 'application/vnd.tcpdump.pcap',
 'sha1': '2c037b8dc499aa18991765ace400d610fbfc7a53',
 'sha256': 'afe45037529455e1f52f7eebcb9f80cb688a8f92cab705a936ff9c18b05cf022',
 'size': 18691200,
 'ssdeep': '393216:85dK09Af39F933tzjQjzxY50Tr5gTOk9IFxGLIDS1Uj:85A0+3T9WHxD5gTODxG2GUj',
 'type': 'network/tcpdump'}
```
It appears as the only thing different between our outputs is the `magic` for the file. However, when I hardcode your magic response into `identify.py`, I still get `network/tcpdump` as the file type.
```
assemblyline@dev-box:~$ sha1sum ~/custom.magic
7202891c41b2276930698fa980be42ec20f5d8e5  ~/custom.magic

assemblyline@dev-box:~$ apt show libmagic1 | grep Version
Version: 1:5.32-2ubuntu0.4
```
Have you made some tweaks to the `custom.magic` file that might affect how it identifies?

**Comment by malvidin** [comment]
Results from running from the ingester container:
```
assemblyline@52b3ab744993:~$ sha1sum /var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline/common/custom.magic
7202891c41b2276930698fa980be42ec20f5d8e5  /var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline/common/custom.magic

assemblyline@52b3ab744993:~$ apt show libmagic1 | grep Version
Version: 1:5.35-4+deb10u2
```

Results from running directly on the core image:
```
$ docker run -ti --rm cccs/assemblyline-core:4.0.0.stable84 sha1sum /var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline/common/custom.magic
7202891c41b2276930698fa980be42ec20f5d8e5  /var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline/common/custom.magic

$ docker run -ti --rm cccs/assemblyline-core:4.0.0.stable84 apt show libmagic1 | grep Version
Version: 1:5.35-4+deb10u2
```

**Comment by cccs-rs** [comment]
This is a weird bug, would you mind providing a `pip freeze | grep assemblyline` of a core and ui container?

Also can you try the following to compare results:
```
ryan@ubuntu:~/Desktop$ pip freeze | grep assemblyline
assemblyline==4.0.0.66
assemblyline-core==4.0.0.84
assemblyline-ui==4.0.1.dev156
ryan@ubuntu:~/Desktop$ python -m assemblyline.common.identify afe45037529455e1f52f7eebcb9f80cb688a8f92cab705a936ff9c18b05cf022
{'ascii': '..........................o]&...V...V.............G...E..H......',
 'entropy': 7.892249519737473,
 'hex': 'd4c3b2a1020004000000000000000000ffff0000010000008bff6f5d26db0d005601000056010000ffffffffffff0008021c47ae080045000148001b00008011',
 'magic': 'pcap capture file, microsecond ts (little-endian) - version 2.4 '
          '(Ethernet, capture length 65535)',
 'md5': 'fad01871bb1bba5fd617818f630bcb1a',
 'mime': 'application/vnd.tcpdump.pcap',
 'sha1': '2c037b8dc499aa18991765ace400d610fbfc7a53',
 'sha256': 'afe45037529455e1f52f7eebcb9f80cb688a8f92cab705a936ff9c18b05cf022',
 'size': 18691200,
 'ssdeep': '393216:85dK09Af39F933tzjQjzxY50Tr5gTOk9IFxGLIDS1Uj:85A0+3T9WHxD5gTODxG2GUj',
 'type': 'network/unknown'}
```

When running identify on the sample, I get 'network/unknown' which matches the magic.
I'm starting to wonder if something else is overwriting the type after the magic results.

**Comment by cccs-kevin** [comment]
Ticket Update: Issue has been confirmed that it is related to the operating system base used by the images. Was able to replicate the issue by testing on a Debian Buster VM. Will keep this thread updated with ticket progress.
