### ISSUE TITLE
Enhancement: Return clearer CLI responses for non-existent Service or User

### ISSUE THREAD

**Issue by malvidin** [CybercentreCanada/assemblyline-base#56]
When a service or user does not exist, the related `remove` command returns `Service 'NX_Service' removed.` or `User 'NX_User' removed.`   It is not clear that no action was taken. 

For the 'show' command, it just returns `None` for both the service and user commands when it does not exist.  This could be more clear.

**Comment by cccs-sgaron** [comment]
PR merged
