### ISSUE TITLE
Better Email Scoring

### ISSUE THREAD

**Issue by malvidin** [CybercentreCanada/assemblyline-base#560]
The strong score of HTML or CSS strings in the body of an email is sometimes larger than the email. Increasing the number of "standard mail" message header fields could increase the accuracy.  To increase the accuracy of identifying an email message containing HTML or CSS vs. HTML/CSS containing an email message, additional logic might be needed.

https://github.com/CybercentreCanada/assemblyline-base/blob/5c153c3e4a1a2ee4080f13328f3cf32e6919f715/assemblyline/common/identify.py#L108-L114

https://www.iana.org/assignments/message-headers/message-headers.xhtml  (protocol: mail, status: standard)

**Comment by cccs-kevin** [comment]
@malvidin Thanks for creating this ticket! Do you have any samples that I could use for testing?

**Comment by malvidin** [comment]
I don't have anything I can share right now. I will share the files directly with you later, after anonymization.
