### ISSUE TITLE
Tiff files are identified as unknown

### ISSUE THREAD

**Issue by foxalfabravo** [CybercentreCanada/assemblyline-base#841]
TIFF File analysis result with 4.2.0.75 as image/unknown
![AL_4_2_0_75](https://user-images.githubusercontent.com/5272992/183079375-347c8312-ea7c-44e4-879c-10250270ef29.png)

TIFF File analysis result with 4.2.0.116 as unknown
![AL_4_2_0_116](https://user-images.githubusercontent.com/5272992/183079378-1424cbf5-feaa-4ec1-af1c-e4b2409e4424.png)

Image
[tiff_file.zip](https://github.com/CybercentreCanada/assemblyline-base/files/9268683/tiff_file.zip)

Mime type shows that it could be identified as image/tiff

**Comment by gdesmar** [comment]
Fixed by PR #843, it should work in the next release.
Thank you!
