### ISSUE TITLE
Suggestion - upgrade os packages on image build

### ISSUE THREAD

**Issue by MalPunch3r** [CybercentreCanada/assemblyline-base#947]
Recently, our vuln scanning software picked up some old vulns in the assemblyline images. (Still actually present in the 4.3.0.stable images). Basically, anything sourced from the base assemblyline image. It turns out that the base image buster-slim, which is what the python:3.9-slim-buster image is based on, was for some reason not fully updated. The buster image was, but not the buster-slim image. They fixed the issue, but it seems like this could be avoided by adding an `apt upgrade` step to the base assemblyline dockerfile.

**Comment by cccs-sgaron** [comment]
These would be the upgraded packages if we were to add an apt upgrade step: 

- ncurses-bin => 6.1+20181013-2+deb10u3
- ncurses-base => 6.1+20181013-2+deb10u3
- libtinfo6 => 6.1+20181013-2+deb10u3
- libncursesw6 => 6.1+20181013-2+deb10u3
- tzdata => 2021a-0+deb10u8
- libexpat1 => 2.2.6-2+deb10u6

Would that fix the issue?

**Comment by MalPunch3r** [comment]
The issue was actually with glibc. If you changed nothing today, and re-ran the pipeline to build the base assemblyline image, that issue would go away as the upstream buster-slim image fixed this about a week ago. 

Looking at our last scan though, it does look like that ncurses package would also fix an issue. 

My point in bringing this up was to put a type of belt and suspenders approach in place by running the package upgrade mechanism as you build the AL images rather than relying that the upstream images are completely up to date.

**Comment by cccs-sgaron** [comment]
Agreed. We will go ahead with adding a `apt upgrade`  call while building the images.
