### ISSUE TITLE
Warning in logs for new service_account feature

### ISSUE THREAD

**Issue by MalPunch3r** [CybercentreCanada/assemblyline-base#973]
With the latest release, 4.3.0.stable32, it looks like there is a minor bug where this is being logged for services that use the new `service_account` spec.

`The following parameters were ignored from object 'DockerConfig': service_account`

Whatever service account is specified is properly being associated to the service. It just seems to be an errant warning in the logs.

**Comment by cccs-rs** [comment]
Hello! This seems to be a result of the services not being rebuilt with the assemblyline-base changes. I will trigger a rebuild for all services which should eliminate these warnings.

**Comment by cccs-rs** [comment]
All stable tags have been rebuilt for most services. Pixaxe seems to have an issue updating which I will look into now.

**Comment by cccs-rs** [comment]
All services have been rebuilt and should no longer generate this warning. Closing issue.
